### ISSUE TITLE
positive/negative filter parameters don't work

### ISSUE THREAD

**Issue by gregcaporaso** [wasade/q2-deblur#18]
They are appending ``--pos-ref-db`` or ``--neg-ref-db`` to the deblur command that is being built, but the actual options in deblur are ~~``--pos-ref-db-fp``~~ ``--pos-ref-fp`` or ~~``--neg-ref-db-fp``~~ ``--neg-ref-fp``.

**Comment by wasade** [comment]
Those are for the preindexed versions of the databases (i.e. result of
indexdb_rna)

cc @amnona

**Comment by gregcaporaso** [comment]
That helps (it explains the current failure that I'm running into in my PR), but the main issue is that the parameters that were being appended [here](https://github.com/wasade/q2-deblur/blob/b598c65a918573e5c4ae903d6088324086570429/q2_deblur/plugin_setup.py#L52) are [not valid parameters](https://github.com/biocore/deblur/blob/0.1.8/scripts/deblur#L402) in the version of deblur that this depends on.

**Comment by wasade** [comment]
Weird, thanks and good catch. I was initially surprised that Travis wasn't [catching](https://github.com/wasade/q2-deblur/blob/master/.travis.yml#L22) it but it's falling back on defaults there.

**Comment by gregcaporaso** [comment]
Yeah, there was no test hitting those branches of the code.
