### ISSUE TITLE
Can't install deblur in Qiime 2: PackageNotFoundError: Package not found: '' Dependencies missing in current osx-64 channels:

### ISSUE THREAD

**Issue by slvrshot** [wasade/q2-deblur#28]
PackageNotFoundError: Package not found: '' Dependencies missing in current osx-64 channels: 
  - q2-deblur -> q2-types ==2017.2.0
  - q2-deblur -> q2cli ==2017.2.0
  - q2-deblur -> qiime2 ==2017.2.0

Close matches found; did you mean one of these?

    qiime2: qiime, r-qiimer

You can search for packages on anaconda.org with

    anaconda search -t conda qiime2

(and similarly for the other packages)

Within the Qiime 2 environment I am running:

(qiime2-2.0.6) Bobby-Mac-Pro:~ twchicken$ conda install -c biocore q2-deblur

**Comment by wasade** [comment]
Hi @slvrshot, it looks like you're within a `2.0.6` QIIME2 environment. `q2-deblur` right now depends on `2017.2.0`. Notes on how to set that environment up can be found [here](https://docs.qiime2.org/2017.2/install/native/#install-qiime-2-within-a-conda-environment). Are you able to verify if this is the issue?

**Comment by slvrshot** [comment]
Stupid mistake @wasade ...so sorry!!! Thank you. I removed the old qiime 2 conda environment and am installing the new qiime 2 environment.

**Comment by wasade** [comment]
No worries at all :)

**Comment by slvrshot** [comment]
@wasade quick question though....is 150 bp the optimal trimmed sequence length for deblur...have you guys tested different lengths? I was just wondering if it even matters. I assume longer lengths might provide better taxonomic resolution but I could be wrong.

**Comment by wasade** [comment]
The author of the method has indicated that longer reads may benefit from modifying the mean error rate as longer reads tend to have poorer quality toward the 3' end, however I'm not aware of data that shows this is actually an issue.
