### ISSUE TITLE
deblur returned non-zero exit status 1

### ISSUE THREAD

**Issue by johnchase** [wasade/q2-deblur#7]
I am running q2-deblur by following the [qiime2 moving pictures tutorial](https://docs.qiime2.org/2.0.6/tutorials/moving-pictures/) except I have replaced the `dada2 denoise` command with `deblur denoise`

```bash
qiime deblur denoise  --i-demultiplexed-seqs demux.qza --o-representative-sequences rep-seqs --o-table table
```

This returns the following error:

```
subprocess.CalledProcessError: Command '['deblur', 'workflow', '--seqs-fp', '/tmp/qiime2-archive-cdd9bdgw/08c4e925-3699-4fde-808a-bfb9025d0c25/data', '--output-dir', '/tmp/tmp93ongdi2', '--mean-error', '0.005', '--error-dist', '1,0.06,0.02,0.02,0.01,0.005,0.005,0.005,0.001,0.001,0.001,0.0005', '--indel-prob', '0.01', '--indel-max', '3', '--trim-length', '100', '--min-reads', '0', '--min-size', '2', '-w']' returned non-zero exit status 1
```

I installed q2-deblur directly from the github repository using pip. Any thought's on what may be causing this error?

**Comment by wasade** [comment]
Can you verify that `deblur` is installed? Ie, just run "deblur workflow --help"

**Comment by johnchase** [comment]
@wasade It is installed. I ran the deblur command directly without using q2-deblur and it appeared to finish with no issues. 

I also tried running q2-deblur using the api and got a different (more informative) error:

`FileNotFoundError: [Errno 2] No such file or directory: 'indexdb_rna'`

**Comment by wasade** [comment]
Ah, thanks. The installation is incomplete. Please see the readme on the Deblur project:

https://github.com/biocore/deblur

`setup.py` won't pull from the conda repos for the non-Python code unfortunately so there a couple of manual steps involved. The README for this repo is supposed to point back to qiime2 docs, but I think we do need at least an INSTALL.md or something.

**Comment by wasade** [comment]
...sorry, more specifically, `indexdb_rna` is a component of SortMeRNA

**Comment by johnchase** [comment]
Yep, that fixed the issue. I don't understand why deblur was working but q2-deblur was not. Regardless it is working now thanks!

**Comment by wasade** [comment]
I think q2-deblur may have been masking the issue unfortunately. Thank you
for reporting it though!

**Comment by carolhuaxia** [comment]
I ran into the same error as the first floor. 
This is my command:
`qiime deblur denoise-16S \
   --i-demultiplexed-seqs meta1-v-j-filtered.qza \
   --p-trim-length -1 \
   --o-representative-sequences rep-seqs-deblur.qza \
   --o-table table-deblur.qza \
   --p-sample-stats \
   --o-stats deblur-stats.qza`
This returns the following error:

> Plugin error from deblur:
> 
>   Command '['deblur', 'workflow', '--seqs-fp', '/tmp/qiime2-archive-3cr3o0wi/967b8294-8193-406e-9433-970e79703255/data', '--output-dir', '/tmp/tmps83knnty', '--mean-error', '0.005', '--indel-prob', '0.01', '--indel-max', '3', '--trim-length', '-1', '--left-trim-length', '0', '--min-reads', '10', '--min-size', '2', '--jobs-to-start', '1', '-w', '--keep-tmp-files']' returned non-zero exit status 1.
> 
> Debug info has been saved to /tmp/qiime2-q2cli-err-vkrlp1ya.log
> 

This is the information in the deblur.log :
[deblur.log](https://github.com/qiime2/q2-deblur/files/3528279/deblur.log)

I have reinstall deblur under the follow command:
`conda activate qiime2-2019.7
conda install -c bioconda -c biocore "VSEARCH=2.7.0" MAFFT=7.310 SortMeRNA=2.0 biom-format deblur`

then I run the "qiime deblur denoise-16S " again, but still return the same error.
It's there any idea about my error. thanks
@wasade

**Comment by carolhuaxia** [comment]
I have already solved the problem. I change the parameter form `--p-trim-length -1` to `--p-trim-length 240`.  Because I got the information "Deblur operates only on same length sequences. " from the web https://forum.qiime2.org/t/deblur-plugin-error/2172
